// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkenumbekpmdvlzukqtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrZW51bWJla3BtZHZsenVrcXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTA3MjgsImV4cCI6MjA2NjM2NjcyOH0.OnUVBsHQLTYd0RrPSxCuWM4DTvNf7GOjtzHQ8-K-PJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);